### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by portlek**

### CODE REVIEW

**Comment by CryptoMorin** [comment]
How does the **${version}** work tho? Is there anywhere I can read about it?

**Comment by portlek** [comment]
> How does the **${version}** work tho? Is there anywhere I can read about it?

It won't work,It's just a placeholder that users should replace with the maven-central case.

**Comment by CryptoMorin** [comment]
I see, can you change it to **version** then? It kinda looks like a bug when you set it as ${version}

**Comment by portlek** [comment]
If I change it, we shall change it every version changing. So this is a problem actually. We may forget to change the version number. Users should know the latest version unless we change it in the readme.

**Comment by CryptoMorin** [comment]
No no. I mean change it to "version". Literally the word "version".

**Comment by portlek** [comment]
alright

**Pull request merged**
