### PR TITLE
[ReflectionUtils] Added world handle and minor/patch version check

### PR DESCRIPTION
**Pull request by stijnb1234**
* Added getHandle() for a World
* Add supports() function with a minor and patch parameter, can be used in reflection where multiple patch versions require different names.

Example:
```java
//1.19.4 and heigher = a
//1.19.3 - 1.13 = b
//1.12 and lower = c
String field = supports(19, 3) ? "a" : supports(13) ? "b" : "c";
```

### CODE REVIEW

**Comment by CryptoMorin** [comment]
You should add the world handle to NMSExtras instead. There's already a field for it, but you can add a dedicated method for it.

**Comment by stijnb1234** [comment]
Why though? I mean, NMSExtras is for stuff related to NMS functions (like thunder), not for reflection stuff. The getHandle for Worlds can be used for almost anything.

**Comment by CryptoMorin** [comment]
> Why though? I mean, NMSExtras is for stuff related to NMS functions (like thunder), not for reflection stuff. The getHandle for Worlds can be used for almost anything.

My (and most other) projects use reflection for NMS inherently. World handle is a NMS function. It's located in `net.minecraft.server`. By your logic, everything in NMSExtras should be moved to ReflectionUtils because it uses reflection.
Your project might use the world handle for "almost everything", but not everyone elses does.

**Comment by CryptoMorin** [comment]
I'm going to close this for inactivity.

**Pull request closed without merging**
