### PR TITLE
Fixed unsupported material with XMaterial#matchItemStack(ItemStack)

### PR DESCRIPTION
**Pull request by Gypopo**
**Description**

Using XMaterial#matchXMaterial(new ItemStack(Material.GREEN_DYE)) says its an unsupported material on **1.13.2**
**Stacktrace:** https://pastebin.com/ByEBTrGM

### CODE REVIEW

**Comment by Gypopo** [comment]
Added a new commit to solve a error with XMaterial#matchXMaterial(POTION) returned a unknown material.

**Comment by Gypopo** [comment]
I also removed the check for if its a monster_egg to check for its SpawnEggMeta since SpawnEggMeta doesn't exist in 1.8 and would also throw a error, you might add this back if its intended.

**Comment by LOOHP** [comment]
Perhaps check whether SpawnEggMeta exists before checking SpawnEggMeta instead?

**Comment by CryptoMorin** [comment]
Yeah, you can't just remove something entirely as a solution.

**Comment by CryptoMorin** [comment]
Fixed in v8.7.0

Btw, SpawnEggMeta exists even in 1.8.8, Idk what version you tested this with.

**Pull request closed without merging**
