### PR TITLE
[XMaterial] Added Reeds as a legacy for SugarCane

### PR DESCRIPTION
**Pull request by IridiumLLC**
Sometimes SugarCane can be referred to as Reeds in 1.8 versions of mc

### CODE REVIEW

**Comment by CryptoMorin** [comment]
What do you mean **sometimes**? Where did you get the Material class source for this? I'm unable to find anything called **REEDS** in any 1.8 version.

**Comment by IridiumLLC** [comment]
> What do you mean **sometimes**? Where did you get the Material class source for this? I'm unable to find anything called **REEDS** in any 1.8 version.

https://minecraft.gamepedia.com/Sugar_Cane

**Comment by CryptoMorin** [comment]
It doesn't mean whatever that's changed in Minecraft's internal code also changes in the Bukkit API. The API never included a material named **REEDS**

**Comment by IridiumLLC** [comment]
The issue is im reading chest contents from a .schematic file, and its parsing back
minecraft:reeds
So I need an easy way to convert this to a material. Unless you know a better way to do this? all the other items seem to be working fine except sugarcane

**Pull request closed without merging**
