### PR TITLE
Fix spawn egg error in 1.8.8 due to missing SpawnEggMeta class.

### PR DESCRIPTION
**Pull request by SirBlobman**
My plugin has the following code to display information about items:
```java
    private String getMaterialNameX(ItemStack item) {
        try {
            XMaterial material = XMaterial.matchXMaterial(item);
            return material.name();
        } catch(IllegalArgumentException ex) {
            return "N/A";
        }
    }
```

Without the fix, the information is wrong when using Spigot 1.8.8:
XSeries_before

When I apply the fix, the information is back to being correct:
XSeries_after

I understand that it is recommended to update to 1.12.2, but some users of my plugin don't want to do that.

### CODE REVIEW

**Comment by CryptoMorin** [comment]
What exactly caused IllegalArgumentException for you? Spawn egg meta works just fine for me in 1.8.8
It'd be nice if you showed the actual stacktrace.

**Comment by SirBlobman** [comment]
> What exactly caused IllegalArgumentException for you? Spawn egg meta works just fine for me in 1.8.8 It'd be nice if you showed the actual stacktrace.


XSeries is moved to the package `com.github.sirblobman.api.xseries.` in my plugin. I am using v8.7.1.

I'm not sure what's going on because I just re-tested it and the original code is working fine. However, I ran a new test where I renamed the item in an anvil and there is a stack trace thrown. This stacktrace is not thrown when I add my fix:

```
[00:28:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'item-info' in plugin SirBlobmanCore v2.3.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/meta/SpawnEggMeta
	at com.github.sirblobman.api.xseries.XMaterial.matchXMaterial(XMaterial.java:1695) ~[?:?]
	at com.github.sirblobman.api.core.command.CommandItemInfo.getMaterialNameX(CommandItemInfo.java:56) ~[?:?]
	at com.github.sirblobman.api.core.command.CommandItemInfo.getInformation(CommandItemInfo.java:82) ~[?:?]
	at com.github.sirblobman.api.core.command.CommandItemInfo.execute(CommandItemInfo.java:42) ~[?:?]
	at com.github.sirblobman.api.command.PlayerCommand.execute(PlayerCommand.java:29) ~[?:?]
	at com.github.sirblobman.api.command.Command.onCommand(Command.java:446) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.meta.SpawnEggMeta
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at com.github.sirblobman.api.xseries.XMaterial.matchXMaterial(XMaterial.java:1695) ~[?:?]
	at com.github.sirblobman.api.core.command.CommandItemInfo.getMaterialNameX(CommandItemInfo.java:56) ~[?:?]
	at com.github.sirblobman.api.core.command.CommandItemInfo.getInformation(CommandItemInfo.java:82) ~[?:?]
	at com.github.sirblobman.api.core.command.CommandItemInfo.execute(CommandItemInfo.java:42) ~[?:?]
	at com.github.sirblobman.api.command.PlayerCommand.execute(PlayerCommand.java:29) ~[?:?]
	at com.github.sirblobman.api.command.Command.onCommand(Command.java:446) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	... 15 more
```

**Comment by CryptoMorin** [comment]
I'm unable to reproduce this using:

> CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by SirBlobman** [comment]
@CryptoMorin I just copied that code to a new plugin and the test did not succeed. I'm not sure what's going on anymore 😐 

**Version:**
```
This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

This error occurs when I click with a WITCH_SPAWN_EGG that has a DISPLAYNAME meta 
**Error:**
```
[16:28:19 ERROR]: Could not pass event PlayerInteractEvent to XSeries-Test v1.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:721) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_332]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/meta/SpawnEggMeta
	at com.cryptomorin.xseries.XMaterial.matchXMaterial(XMaterial.java:1748) ~[?:?]
	at com.github.sirblobman.test.xseries.TestPlugin.onInteract(TestPlugin.java:26) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	... 19 more
```

Once I switch to the version that I wrote, the error no longer occurs.

**Comment by SirBlobman** [comment]
Here is the code for the test plugin if you want to review it.
https://gist.github.com/SirBlobman/a43fccfd3c2a509227a96affaa14e093

**Pull request merged**
