### PR TITLE
Serialization for ParticleDisplay

### PR DESCRIPTION
**Pull request by HSGamer**
Add a method to serialize ParticleDisplay to a ConfigurationSection.

Also add missing getters for particle, count & extra

### CODE REVIEW

**Comment by CryptoMorin** [comment]
I'm assuming you forgot about this, so I'm bumping it.

**Comment by HSGamer** [comment]
> I'm assuming you forgot about this, so I'm bumping it.

It's pretty much completed. Is there anything else?

**Comment by CryptoMorin** [comment]
> > I'm assuming you forgot about this, so I'm bumping it.
> 
> It's pretty much completed. Is there anything else?

Did you see the review I left above?

**Comment by HSGamer** [comment]
> > > I'm assuming you forgot about this, so I'm bumping it.
> > 
> > 
> > It's pretty much completed. Is there anything else?
> 
> Did you see the review I left above?

No, I didn't see any review.

**Comment by CryptoMorin** [comment]
Huh, are you not able to see the image below [here](https://github.com/CryptoMorin/XSeries/pull/210/files/267691e610b281f8eb03c3e0d0e650cdb1ed4709)?
If not I'll just merge it and fix it myself no worries.

image

**Comment by HSGamer** [comment]
> Huh, are you not able to see the image below [here](https://github.com/CryptoMorin/XSeries/pull/210/files/267691e610b281f8eb03c3e0d0e650cdb1ed4709)? If not I'll just merge it and fix it myself no worries. (this is just one of them)
> 
> image

Your review is marked as Pending, you didn't send it, so I didn't see it.

**Review by CryptoMorin — CHANGES_REQUESTED** [review]

**Comment by HSGamer** [comment]
Done

**Comment by CryptoMorin** [comment]
Thank you for taking your time to do this

**Pull request merged**
