### PR TITLE
Adds delegation for Bukkit's configuration section.

### PR DESCRIPTION
**Pull request by portlek**
That allows developers to use serialize/deserialize methods with their own configuration section implementations.

### CODE REVIEW

**Comment by portlek** [comment]
For example, this is my own configuration section interface;
image

**Comment by CryptoMorin** [comment]
I'm planning to use a map instead like you suggested a long time ago. This is just too overkill.

**Comment by portlek** [comment]
> I'm planning to use a map instead like you suggested a long time ago. This is just too overkill.

Yea I suggested but I think this is also a simple way to implement so I did it.

**Comment by portlek** [comment]
Also, about map as a parameter, maybe this may be a little bit buggy or slow because if you want to add backward compatibility for the deserialize/serialize methods, you must make a method that converts the sections in the section map into a real map, It's something like that;
```java
@NotNull
default Map<String, Object> getMapValues(final boolean deep) {
  return this.getValues(deep).entrySet().stream()
    .map(entry -> {
      final var key = entry.getKey();
      final var value = entry.getValue();
      if (value instanceof ConfigurationSection) {
        return new AbstractMap.SimpleEntry<>(key, ((ConfigurationSection) value).getMapValues(deep));
      }
      return new AbstractMap.SimpleEntry<>(key, value);
    })
    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
}
```

**Comment by DeadSilenceIV** [comment]
Hello portlek, i would like to know what would be the benefits of using the **BukkitConfigurationSection** class instead of the normal **ConfigurationSection** class (Just for curiosity).

**Comment by portlek** [comment]
> Hello portlek, i would like to know what would be the benefits of using the **BukkitConfigurationSection** class instead of the normal **ConfigurationSection** class (Just for curiosity).

if someone uses their own configuration section library like Simple-YAML or others, you can't use the serialization method, so XSeries have to use their own configuration section interface on the methods then BukkitConfigurationSection must delegate/wrap the original Bukkit configuration section. That's it. It looks like a stupid idea but it works :D

**Comment by CryptoMorin** [comment]
Right now, the problem is I want to keep these classes as independent as possible.
I'll have to think about it.

**Pull request closed without merging**
